# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - run: deploy.sh
